services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5
  tests:
    build: .
    depends_on:
      - postgres
    command: ["dotnet", "test"]
